feat: change publish trace point definition
tier4/rclcpp pull request #2
Opened 2023-07-14 03:01 UTC by ymski

Some parts of the current CARET define their own trace points. For future development, information that is no longer needed (e.g. message_timestamp in rclcpp_publish) will be removed and the function signatures will be modified to match.

2023-07-14 09:52 UTC, isp-uetsuki requested changes
Is it not required to change the following files?
- rclcpp/include/tracetools/tp_call.h
- rclcpp/include/tracetools/tracetools.h
These files contain definitions of rclcpp_publish and rclcpp_intra_publish.

2023-07-18 01:33 UTC, isp-uetsuki commented
Sorry, files I have mentioned in upper comment are symbolic links to files in another repository. There is no need to modify these files.

2023-07-18 01:34 UTC, isp-uetsuki approved these changes
LGTM

2023-08-04 05:35 UTC, nabetetsu approved these changes
I have confirmed that this fix works as expected in both the humble and iron environments; the iron environment needs an additional fix, but that is supposed to be done in a separate PR.

Here are the tracedata that is used for checking of humble and iron environment.

[humble_evaluate.zip](https://github.com/tier4/rclcpp/files/12257352/humble_evaluate.zip)
[iron_evaluate.zip](https://github.com/tier4/rclcpp/files/12257353/iron_evaluate.zip)

2023-08-09 02:41 UTC, merged